# Generated by Django 5.1.4 on 2024-12-25 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_members',
            field=models.ManyToManyField(related_name='teams', to='Members.member'),
        ),
    ]
