# Generated by Django 5.1.4 on 2024-12-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0002_team_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_members',
        ),
        migrations.AddField(
            model_name='team',
            name='players',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
